{{- range .Values.proxyDNS }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  namespace: {{ .namespace }}
  name: {{ .serviceName }}-{{ randAlphaNum 5 | lower }}
  labels:
    kubernetes.io/service-name: {{ .serviceName }}-service
    site: {{ .serviceName }}
    app: nginx
addressType: IPv4
ports:
  - name: {{ .serviceName }}
    port: {{ .targetPort }}
    protocol: TCP
endpoints:
  {{- range .ips }}
  - addresses:
      - "{{ . }}"
  {{- end }}
{{- end }}
