{{- range .Values.proxyDNS }}
---
apiVersion: discovery.k8s.io/v1
kind: Endpoints
metadata:
  namespace: {{ .namespace }}
  name: {{ .serviceName }}-service
  labels:
    site: {{ .serviceName }}
    app: nginx
subsets:
- addresses:
    {{- range .ips }}
    - ip: {{ . }}
    {{- end }}
  ports:
  - name: {{ .serviceName }}
    port: {{ .targetPort }}
    protocol: TCP
{{- end }}
